### ISSUE TITLE
'Decodable' is ambiguous for type lookup in this context

### ISSUE THREAD

**Issue by mwapptest** [spxrogers/Moya-Gloss#28]
Hi,

I am using latest Xcode 9.0 and pod with 'Moya' & 'Moya-Gloss'. It was working fine in Xcode 8.3.2 but new Xocde 9.0 showing me during compilation error

/Pods/Moya-Gloss/Source/Response+Gloss.swift
'Decodable' is ambiguous for type lookup in this context
Non-nominal type 'T' does not support explicit initialization

**Comment by spxrogers** [comment]
@mwapptest which version of `Moya-Gloss` are you using?

**Comment by mdwagh** [comment]
Hi, I am using via pod 'Moya-Gloss', as per General setting is showing me 'Using Moya-Gloss (2.0.1)'

**Comment by spxrogers** [comment]
hi @mwapptest, your `Podfile.lock` file has you locked into an older version — and the error you are seeing has been fixed since then.

please run `pod update Moya-Gloss` to get the [latest version](https://github.com/spxrogers/Moya-Gloss/releases/tag/2.0.3) and i hope that helps!

please open a new issue if there are any more problems.
